# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180327_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
