# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
    ]
