# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_project_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
