# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_auto_20180403_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_workables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
