# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_my_workables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'Results'},
        ),
    ]
